name: Scrape jobs

on:
  schedule:
    - cron: '0 */2 * * *' # Run every 2 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  run-automation:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "AIRTABLE_API_KEY=${{ secrets.AIRTABLE_API_KEY }}" >> .env

      - name: Install dependencies
        run: make install

      - name: Run job search
        run: make search
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
