name: Scrape jobs (with Tunnel)

on:
  schedule:
    - cron: '0 */2 * * *' # Run every 2 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Cloudflare Tunnel
        if: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
        run: |
          # Install cloudflared
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
          
          # Start tunnel in background
          cloudflared tunnel --token ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }} &
          sleep 10  # Wait for tunnel to establish

      - name: Setup ngrok tunnel (alternative)
        if: ${{ secrets.NGROK_AUTH_TOKEN && !secrets.CLOUDFLARE_TUNNEL_TOKEN }}
        run: |
          # Install ngrok
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok
          
          # Authenticate and start tunnel
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok http 80 &
          sleep 10

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "AIRTABLE_API_KEY=${{ secrets.AIRTABLE_API_KEY }}" >> .env

      - name: Run automation script
        run: scripts/run_job_search.sh
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
